### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [salamantos/zoo_sh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by salamantos** [comment]
Hello! Thank you for your interest.

I added the MIT license. And I'll be glad to see my project in awesome-zsh-plugins)
